version: 0.0
os: linux
files:
  - source: /
    destination: /var/fipman/uploader/
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: ubuntu
      timeout: 3000
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: ubuntu
      timeout: 60